# lightbulb/docker-compose.yml

version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
